//! Embedded SPA static file serving.
//!
//! Includes the Vite build output (`web/dist/`) at compile time via
//! `include_bytes!` entries generated by `build.rs`.  Serves files
//! with correct `Content-Type` headers.
//!
//! When the `embed-frontend` feature is disabled, all lookups return
//! `None` and the SPA routes return 404.

use desmos_http::request::Request;
use desmos_http::response::Response;
use desmos_http::router::Params;

// Pull in the generated file lookup table.
include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));

/// Serve the SPA root (`GET /`).
///
/// Returns `index.html` from the embedded bundle.
pub fn spa_root(_req: &Request<'_>, _params: &Params) -> Response {
    match lookup("/") {
        Some((content_type, data)) => {
            let mut r = Response::ok();
            r.body_raw(content_type, data.to_vec());
            r
        }
        None => Response::not_found(),
    }
}

/// Serve a static asset (`GET /assets/*`).
///
/// The path is taken directly from the request URI.
pub fn spa_static(req: &Request<'_>, _params: &Params) -> Response {
    let path = req.path();

    match lookup(path) {
        Some((content_type, data)) => {
            let mut r = Response::ok();
            r.body_raw(content_type, data.to_vec());
            // Immutable assets (hashed filenames) can be cached aggressively.
            if path.contains("/assets/") {
                r.header("Cache-Control", "public, max-age=31536000, immutable");
            }
            r
        }
        None => Response::not_found(),
    }
}

/// Number of files embedded in the binary.
pub fn file_count() -> usize {
    EMBEDDED_FILE_COUNT
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use desmos_http::headers::Headers;
    use desmos_http::method::Method;

    fn make_get(uri: &str) -> Request<'_> {
        Request { method: Method::Get, uri, headers: Headers::empty(), body: Vec::new() }
    }

    #[test]
    fn spa_root_serves_index_html() {
        let req = make_get("/");
        let resp = spa_root(&req, &Params::new());

        if EMBEDDED_FILE_COUNT > 0 {
            assert_eq!(resp.status, desmos_http::StatusCode::OK);
            let body = std::str::from_utf8(resp.body()).unwrap();
            assert!(body.contains("<!DOCTYPE html>") || body.contains("<html"));
        } else {
            // No frontend embedded (feature disabled).
            assert_eq!(resp.status, desmos_http::StatusCode::NOT_FOUND);
        }
    }

    #[test]
    fn spa_static_unknown_returns_404() {
        let req = make_get("/assets/nonexistent.js");
        let resp = spa_static(&req, &Params::new());
        assert_eq!(resp.status, desmos_http::StatusCode::NOT_FOUND);
    }

    #[test]
    fn file_count_matches_feature() {
        let count = file_count();
        if cfg!(feature = "embed-frontend") {
            // With the feature, there should be at least index.html.
            assert!(count > 0, "expected embedded files with embed-frontend feature");
        } else {
            assert_eq!(count, 0);
        }
    }

    #[test]
    fn lookup_root_returns_index_html() {
        if EMBEDDED_FILE_COUNT > 0 {
            let (ct, data) = lookup("/").unwrap();
            assert!(ct.contains("text/html"));
            assert!(!data.is_empty());
        }
    }

    #[test]
    fn lookup_unknown_returns_none() {
        assert!(lookup("/does/not/exist.xyz").is_none());
    }
}
